// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/mediabase/v1/mediabase.proto

package mediabase_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateBucketRequest contains the bucket name and public access preference
type CreateBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	IsPublic      bool                   `protobuf:"varint,2,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketRequest) Reset() {
	*x = CreateBucketRequest{}
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketRequest) ProtoMessage() {}

func (x *CreateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketRequest.ProtoReflect.Descriptor instead.
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediabase_v1_mediabase_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *CreateBucketRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

// CreateBucketResponse indicates successful creation
type CreateBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketResponse) Reset() {
	*x = CreateBucketResponse{}
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketResponse) ProtoMessage() {}

func (x *CreateBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketResponse.ProtoReflect.Descriptor instead.
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return file_proto_mediabase_v1_mediabase_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBucketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PresignUploadRequest contains the parameters for generating a presigned upload URL
type PresignUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bucket name where the file should be uploaded
	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// Content type of the file (e.g., "image/jpeg", "image/png", "image/webp")
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Maximum allowed size of the file in bytes (will be enforced by storage)
	MaxFileSize int64 `protobuf:"varint,3,opt,name=max_file_size,json=maxFileSize,proto3" json:"max_file_size,omitempty"`
	// Optional: Path/Folder where the file should be uploaded (e.g., "users/avatars")
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// Optional: Exact filename to use. If not provided, a unique UUID will be generated.
	FileName      string `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignUploadRequest) Reset() {
	*x = PresignUploadRequest{}
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignUploadRequest) ProtoMessage() {}

func (x *PresignUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignUploadRequest.ProtoReflect.Descriptor instead.
func (*PresignUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediabase_v1_mediabase_proto_rawDescGZIP(), []int{2}
}

func (x *PresignUploadRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *PresignUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PresignUploadRequest) GetMaxFileSize() int64 {
	if x != nil {
		return x.MaxFileSize
	}
	return 0
}

func (x *PresignUploadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PresignUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// PresignUploadResponse contains the presigned URL and metadata
type PresignUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Presigned URL for uploading the file
	PresignedUrl string `protobuf:"bytes,1,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	// Object key/path in storage
	ObjectKey string `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	// Expiration time in seconds
	ExpiresIn int32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// Optional: Form data fields for POST upload (required for size enforcement)
	FormData      map[string]string `protobuf:"bytes,4,rep,name=form_data,json=formData,proto3" json:"form_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignUploadResponse) Reset() {
	*x = PresignUploadResponse{}
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignUploadResponse) ProtoMessage() {}

func (x *PresignUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignUploadResponse.ProtoReflect.Descriptor instead.
func (*PresignUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_mediabase_v1_mediabase_proto_rawDescGZIP(), []int{3}
}

func (x *PresignUploadResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

func (x *PresignUploadResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *PresignUploadResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *PresignUploadResponse) GetFormData() map[string]string {
	if x != nil {
		return x.FormData
	}
	return nil
}

// PresignDownloadRequest contains the object key for download
type PresignDownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bucket name where the file is stored
	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// Object key/path in storage
	ObjectKey     string `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignDownloadRequest) Reset() {
	*x = PresignDownloadRequest{}
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignDownloadRequest) ProtoMessage() {}

func (x *PresignDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignDownloadRequest.ProtoReflect.Descriptor instead.
func (*PresignDownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediabase_v1_mediabase_proto_rawDescGZIP(), []int{4}
}

func (x *PresignDownloadRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *PresignDownloadRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

// PresignDownloadResponse contains the presigned download URL
type PresignDownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Presigned URL for downloading the file
	PresignedUrl string `protobuf:"bytes,1,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	// Expiration time in seconds
	ExpiresIn     int32 `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignDownloadResponse) Reset() {
	*x = PresignDownloadResponse{}
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignDownloadResponse) ProtoMessage() {}

func (x *PresignDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignDownloadResponse.ProtoReflect.Descriptor instead.
func (*PresignDownloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_mediabase_v1_mediabase_proto_rawDescGZIP(), []int{5}
}

func (x *PresignDownloadResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

func (x *PresignDownloadResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// DeleteObjectRequest contains the object key to delete
type DeleteObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bucket name where the file is stored
	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// Object key/path in storage
	ObjectKey     string `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectRequest) Reset() {
	*x = DeleteObjectRequest{}
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectRequest) ProtoMessage() {}

func (x *DeleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediabase_v1_mediabase_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteObjectRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *DeleteObjectRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

// DeleteObjectResponse indicates successful deletion
type DeleteObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deletion was successful
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectResponse) Reset() {
	*x = DeleteObjectResponse{}
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectResponse) ProtoMessage() {}

func (x *DeleteObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediabase_v1_mediabase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_mediabase_v1_mediabase_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteObjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_mediabase_v1_mediabase_proto protoreflect.FileDescriptor

const file_proto_mediabase_v1_mediabase_proto_rawDesc = "" +
	"\n" +
	"\"proto/mediabase/v1/mediabase.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1dproto/mediabase/v1/ping.proto\x1a\x17validate/validate.proto\"\\\n" +
	"\x13CreateBucketRequest\x12(\n" +
	"\vbucket_name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"bucketName\x12\x1b\n" +
	"\tis_public\x18\x02 \x01(\bR\bisPublic\"0\n" +
	"\x14CreateBucketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xca\x01\n" +
	"\x14PresignUploadRequest\x12(\n" +
	"\vbucket_name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"bucketName\x12*\n" +
	"\fcontent_type\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vcontentType\x12+\n" +
	"\rmax_file_size\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\vmaxFileSize\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\"\xfd\x01\n" +
	"\x15PresignUploadResponse\x12#\n" +
	"\rpresigned_url\x18\x01 \x01(\tR\fpresignedUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\x12D\n" +
	"\tform_data\x18\x04 \x03(\v2'.v1.PresignUploadResponse.FormDataEntryR\bformData\x1a;\n" +
	"\rFormDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x16PresignDownloadRequest\x12(\n" +
	"\vbucket_name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"bucketName\x12&\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tobjectKey\"]\n" +
	"\x17PresignDownloadResponse\x12#\n" +
	"\rpresigned_url\x18\x01 \x01(\tR\fpresignedUrl\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x05R\texpiresIn\"g\n" +
	"\x13DeleteObjectRequest\x12(\n" +
	"\vbucket_name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"bucketName\x12&\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tobjectKey\"0\n" +
	"\x14DeleteObjectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf4\a\n" +
	"\x10MediabaseService\x12~\n" +
	"\x04Ping\x12\x0f.v1.PingRequest\x1a\x10.v1.PingResponse\"S\x92A6\n" +
	"\x04Ping\x12\x0fPing the server\x1a\x1dCheck if the server is alive.\x82\xd3\xe4\x93\x02\x14\x12\x12/mediabase/v1/ping\x12\xd9\x01\n" +
	"\rPresignUpload\x12\x18.v1.PresignUploadRequest\x1a\x19.v1.PresignUploadResponse\"\x92\x01\x92Aj\n" +
	"\x06Upload\x12\x1dGenerate presigned upload URL\x1aAReturns a presigned URL for uploading a file directly to storage.\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/upload/presign/upload\x12\xde\x01\n" +
	"\x0fPresignDownload\x12\x1a.v1.PresignDownloadRequest\x1a\x1b.v1.PresignDownloadResponse\"\x91\x01\x92Ag\n" +
	"\x06Upload\x12\x1fGenerate presigned download URL\x1a<Returns a presigned URL for downloading a file from storage.\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/upload/presign/download\x12\xa2\x01\n" +
	"\fDeleteObject\x12\x17.v1.DeleteObjectRequest\x1a\x18.v1.DeleteObjectResponse\"_\x92A5\n" +
	"\x06Upload\x12\rDelete object\x1a\x1cDeletes a file from storage.\x82\xd3\xe4\x93\x02!*\x1f/api/upload/object/{object_key}\x12\xfd\x01\n" +
	"\fCreateBucket\x12\x17.v1.CreateBucketRequest\x1a\x18.v1.CreateBucketResponse\"\xb9\x01\x92A\x98\x01\n" +
	"\x06Upload\x12\rCreate bucket\x1a\x7fCreates a bucket and optionally sets its policy to allow public read access while keeping uploads private (via presigned URLs).\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/upload/bucketB\xd8\x01\x92A\xc4\x01\x12q\n" +
	"\rmediabase API\x12Xmediabase is a generic media storage service supporting presigned uploads and downloads.2\x06v1.0.0j\x1e\n" +
	"\x04Ping\x12\x16Health check endpointsj/\n" +
	"\x06Upload\x12%Media upload and management endpointsZ\x0e./mediabase_v1b\x06proto3"

var (
	file_proto_mediabase_v1_mediabase_proto_rawDescOnce sync.Once
	file_proto_mediabase_v1_mediabase_proto_rawDescData []byte
)

func file_proto_mediabase_v1_mediabase_proto_rawDescGZIP() []byte {
	file_proto_mediabase_v1_mediabase_proto_rawDescOnce.Do(func() {
		file_proto_mediabase_v1_mediabase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mediabase_v1_mediabase_proto_rawDesc), len(file_proto_mediabase_v1_mediabase_proto_rawDesc)))
	})
	return file_proto_mediabase_v1_mediabase_proto_rawDescData
}

var file_proto_mediabase_v1_mediabase_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_mediabase_v1_mediabase_proto_goTypes = []any{
	(*CreateBucketRequest)(nil),     // 0: v1.CreateBucketRequest
	(*CreateBucketResponse)(nil),    // 1: v1.CreateBucketResponse
	(*PresignUploadRequest)(nil),    // 2: v1.PresignUploadRequest
	(*PresignUploadResponse)(nil),   // 3: v1.PresignUploadResponse
	(*PresignDownloadRequest)(nil),  // 4: v1.PresignDownloadRequest
	(*PresignDownloadResponse)(nil), // 5: v1.PresignDownloadResponse
	(*DeleteObjectRequest)(nil),     // 6: v1.DeleteObjectRequest
	(*DeleteObjectResponse)(nil),    // 7: v1.DeleteObjectResponse
	nil,                             // 8: v1.PresignUploadResponse.FormDataEntry
	(*PingRequest)(nil),             // 9: v1.PingRequest
	(*PingResponse)(nil),            // 10: v1.PingResponse
}
var file_proto_mediabase_v1_mediabase_proto_depIdxs = []int32{
	8,  // 0: v1.PresignUploadResponse.form_data:type_name -> v1.PresignUploadResponse.FormDataEntry
	9,  // 1: v1.MediabaseService.Ping:input_type -> v1.PingRequest
	2,  // 2: v1.MediabaseService.PresignUpload:input_type -> v1.PresignUploadRequest
	4,  // 3: v1.MediabaseService.PresignDownload:input_type -> v1.PresignDownloadRequest
	6,  // 4: v1.MediabaseService.DeleteObject:input_type -> v1.DeleteObjectRequest
	0,  // 5: v1.MediabaseService.CreateBucket:input_type -> v1.CreateBucketRequest
	10, // 6: v1.MediabaseService.Ping:output_type -> v1.PingResponse
	3,  // 7: v1.MediabaseService.PresignUpload:output_type -> v1.PresignUploadResponse
	5,  // 8: v1.MediabaseService.PresignDownload:output_type -> v1.PresignDownloadResponse
	7,  // 9: v1.MediabaseService.DeleteObject:output_type -> v1.DeleteObjectResponse
	1,  // 10: v1.MediabaseService.CreateBucket:output_type -> v1.CreateBucketResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_mediabase_v1_mediabase_proto_init() }
func file_proto_mediabase_v1_mediabase_proto_init() {
	if File_proto_mediabase_v1_mediabase_proto != nil {
		return
	}
	file_proto_mediabase_v1_ping_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mediabase_v1_mediabase_proto_rawDesc), len(file_proto_mediabase_v1_mediabase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mediabase_v1_mediabase_proto_goTypes,
		DependencyIndexes: file_proto_mediabase_v1_mediabase_proto_depIdxs,
		MessageInfos:      file_proto_mediabase_v1_mediabase_proto_msgTypes,
	}.Build()
	File_proto_mediabase_v1_mediabase_proto = out.File
	file_proto_mediabase_v1_mediabase_proto_goTypes = nil
	file_proto_mediabase_v1_mediabase_proto_depIdxs = nil
}
