// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/mediabase/v1/mediabase.proto

package mediabase_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediabaseService_Ping_FullMethodName            = "/v1.MediabaseService/Ping"
	MediabaseService_PresignUpload_FullMethodName   = "/v1.MediabaseService/PresignUpload"
	MediabaseService_PresignDownload_FullMethodName = "/v1.MediabaseService/PresignDownload"
	MediabaseService_DeleteObject_FullMethodName    = "/v1.MediabaseService/DeleteObject"
	MediabaseService_CreateBucket_FullMethodName    = "/v1.MediabaseService/CreateBucket"
)

// MediabaseServiceClient is the client API for MediabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediabaseServiceClient interface {
	// Ping is a simple GET request that returns a Pong message.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// PresignUpload generates a presigned URL for uploading a file
	PresignUpload(ctx context.Context, in *PresignUploadRequest, opts ...grpc.CallOption) (*PresignUploadResponse, error)
	// PresignDownload generates a presigned URL for downloading a file
	PresignDownload(ctx context.Context, in *PresignDownloadRequest, opts ...grpc.CallOption) (*PresignDownloadResponse, error)
	// DeleteObject deletes a file from storage
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	// CreateBucket creates a bucket and optionally sets it to public read
	CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error)
}

type mediabaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediabaseServiceClient(cc grpc.ClientConnInterface) MediabaseServiceClient {
	return &mediabaseServiceClient{cc}
}

func (c *mediabaseServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, MediabaseService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediabaseServiceClient) PresignUpload(ctx context.Context, in *PresignUploadRequest, opts ...grpc.CallOption) (*PresignUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignUploadResponse)
	err := c.cc.Invoke(ctx, MediabaseService_PresignUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediabaseServiceClient) PresignDownload(ctx context.Context, in *PresignDownloadRequest, opts ...grpc.CallOption) (*PresignDownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignDownloadResponse)
	err := c.cc.Invoke(ctx, MediabaseService_PresignDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediabaseServiceClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, MediabaseService_DeleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediabaseServiceClient) CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBucketResponse)
	err := c.cc.Invoke(ctx, MediabaseService_CreateBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediabaseServiceServer is the server API for MediabaseService service.
// All implementations must embed UnimplementedMediabaseServiceServer
// for forward compatibility.
type MediabaseServiceServer interface {
	// Ping is a simple GET request that returns a Pong message.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// PresignUpload generates a presigned URL for uploading a file
	PresignUpload(context.Context, *PresignUploadRequest) (*PresignUploadResponse, error)
	// PresignDownload generates a presigned URL for downloading a file
	PresignDownload(context.Context, *PresignDownloadRequest) (*PresignDownloadResponse, error)
	// DeleteObject deletes a file from storage
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	// CreateBucket creates a bucket and optionally sets it to public read
	CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error)
	mustEmbedUnimplementedMediabaseServiceServer()
}

// UnimplementedMediabaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediabaseServiceServer struct{}

func (UnimplementedMediabaseServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMediabaseServiceServer) PresignUpload(context.Context, *PresignUploadRequest) (*PresignUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PresignUpload not implemented")
}
func (UnimplementedMediabaseServiceServer) PresignDownload(context.Context, *PresignDownloadRequest) (*PresignDownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PresignDownload not implemented")
}
func (UnimplementedMediabaseServiceServer) DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedMediabaseServiceServer) CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBucket not implemented")
}
func (UnimplementedMediabaseServiceServer) mustEmbedUnimplementedMediabaseServiceServer() {}
func (UnimplementedMediabaseServiceServer) testEmbeddedByValue()                          {}

// UnsafeMediabaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediabaseServiceServer will
// result in compilation errors.
type UnsafeMediabaseServiceServer interface {
	mustEmbedUnimplementedMediabaseServiceServer()
}

func RegisterMediabaseServiceServer(s grpc.ServiceRegistrar, srv MediabaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedMediabaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediabaseService_ServiceDesc, srv)
}

func _MediabaseService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediabaseServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediabaseService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediabaseServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediabaseService_PresignUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediabaseServiceServer).PresignUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediabaseService_PresignUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediabaseServiceServer).PresignUpload(ctx, req.(*PresignUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediabaseService_PresignDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediabaseServiceServer).PresignDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediabaseService_PresignDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediabaseServiceServer).PresignDownload(ctx, req.(*PresignDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediabaseService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediabaseServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediabaseService_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediabaseServiceServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediabaseService_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediabaseServiceServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediabaseService_CreateBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediabaseServiceServer).CreateBucket(ctx, req.(*CreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediabaseService_ServiceDesc is the grpc.ServiceDesc for MediabaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediabaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MediabaseService",
	HandlerType: (*MediabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _MediabaseService_Ping_Handler,
		},
		{
			MethodName: "PresignUpload",
			Handler:    _MediabaseService_PresignUpload_Handler,
		},
		{
			MethodName: "PresignDownload",
			Handler:    _MediabaseService_PresignDownload_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _MediabaseService_DeleteObject_Handler,
		},
		{
			MethodName: "CreateBucket",
			Handler:    _MediabaseService_CreateBucket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mediabase/v1/mediabase.proto",
}
