// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/mediabase/v1/mediabase.proto

package mediabase_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateBucketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBucketRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBucketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBucketRequestMultiError, or nil if none found.
func (m *CreateBucketRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBucketRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBucketName()) < 1 {
		err := CreateBucketRequestValidationError{
			field:  "BucketName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsPublic

	if len(errors) > 0 {
		return CreateBucketRequestMultiError(errors)
	}

	return nil
}

// CreateBucketRequestMultiError is an error wrapping multiple validation
// errors returned by CreateBucketRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateBucketRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBucketRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBucketRequestMultiError) AllErrors() []error { return m }

// CreateBucketRequestValidationError is the validation error returned by
// CreateBucketRequest.Validate if the designated constraints aren't met.
type CreateBucketRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBucketRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBucketRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBucketRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBucketRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBucketRequestValidationError) ErrorName() string {
	return "CreateBucketRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBucketRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBucketRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBucketRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBucketRequestValidationError{}

// Validate checks the field values on CreateBucketResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBucketResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBucketResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBucketResponseMultiError, or nil if none found.
func (m *CreateBucketResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBucketResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return CreateBucketResponseMultiError(errors)
	}

	return nil
}

// CreateBucketResponseMultiError is an error wrapping multiple validation
// errors returned by CreateBucketResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateBucketResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBucketResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBucketResponseMultiError) AllErrors() []error { return m }

// CreateBucketResponseValidationError is the validation error returned by
// CreateBucketResponse.Validate if the designated constraints aren't met.
type CreateBucketResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBucketResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBucketResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBucketResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBucketResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBucketResponseValidationError) ErrorName() string {
	return "CreateBucketResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBucketResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBucketResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBucketResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBucketResponseValidationError{}

// Validate checks the field values on PresignUploadRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PresignUploadRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PresignUploadRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PresignUploadRequestMultiError, or nil if none found.
func (m *PresignUploadRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PresignUploadRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBucketName()) < 1 {
		err := PresignUploadRequestValidationError{
			field:  "BucketName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetContentType()) < 1 {
		err := PresignUploadRequestValidationError{
			field:  "ContentType",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetMaxFileSize() <= 0 {
		err := PresignUploadRequestValidationError{
			field:  "MaxFileSize",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Path

	// no validation rules for FileName

	if len(errors) > 0 {
		return PresignUploadRequestMultiError(errors)
	}

	return nil
}

// PresignUploadRequestMultiError is an error wrapping multiple validation
// errors returned by PresignUploadRequest.ValidateAll() if the designated
// constraints aren't met.
type PresignUploadRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PresignUploadRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PresignUploadRequestMultiError) AllErrors() []error { return m }

// PresignUploadRequestValidationError is the validation error returned by
// PresignUploadRequest.Validate if the designated constraints aren't met.
type PresignUploadRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PresignUploadRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PresignUploadRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PresignUploadRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PresignUploadRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PresignUploadRequestValidationError) ErrorName() string {
	return "PresignUploadRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PresignUploadRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPresignUploadRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PresignUploadRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PresignUploadRequestValidationError{}

// Validate checks the field values on PresignUploadResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PresignUploadResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PresignUploadResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PresignUploadResponseMultiError, or nil if none found.
func (m *PresignUploadResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PresignUploadResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PresignedUrl

	// no validation rules for ObjectKey

	// no validation rules for ExpiresIn

	// no validation rules for FormData

	if len(errors) > 0 {
		return PresignUploadResponseMultiError(errors)
	}

	return nil
}

// PresignUploadResponseMultiError is an error wrapping multiple validation
// errors returned by PresignUploadResponse.ValidateAll() if the designated
// constraints aren't met.
type PresignUploadResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PresignUploadResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PresignUploadResponseMultiError) AllErrors() []error { return m }

// PresignUploadResponseValidationError is the validation error returned by
// PresignUploadResponse.Validate if the designated constraints aren't met.
type PresignUploadResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PresignUploadResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PresignUploadResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PresignUploadResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PresignUploadResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PresignUploadResponseValidationError) ErrorName() string {
	return "PresignUploadResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PresignUploadResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPresignUploadResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PresignUploadResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PresignUploadResponseValidationError{}

// Validate checks the field values on PresignDownloadRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PresignDownloadRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PresignDownloadRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PresignDownloadRequestMultiError, or nil if none found.
func (m *PresignDownloadRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PresignDownloadRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBucketName()) < 1 {
		err := PresignDownloadRequestValidationError{
			field:  "BucketName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetObjectKey()) < 1 {
		err := PresignDownloadRequestValidationError{
			field:  "ObjectKey",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PresignDownloadRequestMultiError(errors)
	}

	return nil
}

// PresignDownloadRequestMultiError is an error wrapping multiple validation
// errors returned by PresignDownloadRequest.ValidateAll() if the designated
// constraints aren't met.
type PresignDownloadRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PresignDownloadRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PresignDownloadRequestMultiError) AllErrors() []error { return m }

// PresignDownloadRequestValidationError is the validation error returned by
// PresignDownloadRequest.Validate if the designated constraints aren't met.
type PresignDownloadRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PresignDownloadRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PresignDownloadRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PresignDownloadRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PresignDownloadRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PresignDownloadRequestValidationError) ErrorName() string {
	return "PresignDownloadRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PresignDownloadRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPresignDownloadRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PresignDownloadRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PresignDownloadRequestValidationError{}

// Validate checks the field values on PresignDownloadResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PresignDownloadResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PresignDownloadResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PresignDownloadResponseMultiError, or nil if none found.
func (m *PresignDownloadResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PresignDownloadResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PresignedUrl

	// no validation rules for ExpiresIn

	if len(errors) > 0 {
		return PresignDownloadResponseMultiError(errors)
	}

	return nil
}

// PresignDownloadResponseMultiError is an error wrapping multiple validation
// errors returned by PresignDownloadResponse.ValidateAll() if the designated
// constraints aren't met.
type PresignDownloadResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PresignDownloadResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PresignDownloadResponseMultiError) AllErrors() []error { return m }

// PresignDownloadResponseValidationError is the validation error returned by
// PresignDownloadResponse.Validate if the designated constraints aren't met.
type PresignDownloadResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PresignDownloadResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PresignDownloadResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PresignDownloadResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PresignDownloadResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PresignDownloadResponseValidationError) ErrorName() string {
	return "PresignDownloadResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PresignDownloadResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPresignDownloadResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PresignDownloadResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PresignDownloadResponseValidationError{}

// Validate checks the field values on DeleteObjectRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteObjectRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteObjectRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteObjectRequestMultiError, or nil if none found.
func (m *DeleteObjectRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteObjectRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBucketName()) < 1 {
		err := DeleteObjectRequestValidationError{
			field:  "BucketName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetObjectKey()) < 1 {
		err := DeleteObjectRequestValidationError{
			field:  "ObjectKey",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteObjectRequestMultiError(errors)
	}

	return nil
}

// DeleteObjectRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteObjectRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteObjectRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteObjectRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteObjectRequestMultiError) AllErrors() []error { return m }

// DeleteObjectRequestValidationError is the validation error returned by
// DeleteObjectRequest.Validate if the designated constraints aren't met.
type DeleteObjectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteObjectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteObjectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteObjectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteObjectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteObjectRequestValidationError) ErrorName() string {
	return "DeleteObjectRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteObjectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteObjectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteObjectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteObjectRequestValidationError{}

// Validate checks the field values on DeleteObjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteObjectResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteObjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteObjectResponseMultiError, or nil if none found.
func (m *DeleteObjectResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteObjectResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return DeleteObjectResponseMultiError(errors)
	}

	return nil
}

// DeleteObjectResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteObjectResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteObjectResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteObjectResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteObjectResponseMultiError) AllErrors() []error { return m }

// DeleteObjectResponseValidationError is the validation error returned by
// DeleteObjectResponse.Validate if the designated constraints aren't met.
type DeleteObjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteObjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteObjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteObjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteObjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteObjectResponseValidationError) ErrorName() string {
	return "DeleteObjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteObjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteObjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteObjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteObjectResponseValidationError{}
