apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediabase
  labels:
    app: mediabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediabase
  template:
    metadata:
      labels:
        app: mediabase
    spec:
      containers:
        - name: mediabase
          image: ghcr.io/gofreego/mediabase:pilot-65abd30
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
            - name: grpc
              containerPort: 8081
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
