apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediabase
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - media.zshala.com
      secretName: media-zshala-com-tls
  rules:
    - host: media.zshala.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mediabase
                port:
                  name: http
